travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -20,15 +20,30 @@ install: |
   # Prepare the COQ container
   docker pull "${DOCKERIMAGE}"
   docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} "${DOCKERIMAGE}"
+  docker exec COQ /bin/bash --login -c "
+    # This bash script is double-quoted to interpolate Travis CI env vars:
+    echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
+    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
+    set -ex  # -e = exit on failure; -x = trace for debug
+    # Using flambda makes sense here as we usually get ~10% faster
+    # builds in math-comp.
+    opam switch \$COMPILER_EDGE
+    opam update -y
+    opam config list
+    opam repo list
+    opam list
+    sudo chown -R coq:coq /home/coq/${CONTRIB_NAME}
+    opam pin add -y -n robbins .
+    opam install -y -vvv --deps-only robbins
+    "
+
 script:
 - echo -e "${ANSI_YELLOW}Building ${CONTRIB_NAME}...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
 - |
   docker exec COQ /bin/bash --login -c "
     export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
     set -ex
-    echo "tooto"
-    pwd
-    ls
+    opam install -y -vvv robbins
     "
 - docker stop COQ  # optional
 - echo -en 'travis_fold:end:script\\r'
